/// Flutter icons PhithanGreen
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PhithanGreen
///      fonts:
///       - asset: fonts/PhithanGreen.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PhithanGreen {
  PhithanGreen._();

  static const _kFontFam = 'PhithanGreen';
  static const String _kFontPkg = null;

  static const IconData phithan_28 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_27 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_26 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_25 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_24 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_23 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_22 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_21 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_20 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_19 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_17 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_18 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_16 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_15 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_14 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_13 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_12 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_11 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_10 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_09 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_08 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_07 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_06 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_05 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_04 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_03 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_02 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_01 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_90 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_89 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_88 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_87 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_86 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_85 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_84 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_83 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_82 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_81 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_80 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_79 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_78 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_77 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_76 = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_75 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_74 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_73 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_72 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_71 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_70 = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_69 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_68 = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_67 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_66 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_65 = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_64 = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_63 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_62 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_61 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_60 = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_59 = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_58 = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_57 = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_56 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_55 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_54 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_53 = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_52 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_51 = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_50 = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_49 = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_48 = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_47 = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_46 = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_45 = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_44 = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_43 = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_42 = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_41 = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_40 = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_39 = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_38 = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_37 = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_36 = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_35 = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_34 = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_33 = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_32 = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_31 = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_30 = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phithan_29 = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
